sudo: required
services:
  - docker

matrix:
    allow_failures:

cache: bundler

install:
    - docker build -t rock-osdeps/16.04 -f Dockerfile-16.04 --build-arg PKGSET_BRANCH=rock-osdeps-test .
    - docker run -d rock-osdeps/16.04 tail -f /dev/null
    - docker build -t rock-osdeps/18.04 -f Dockerfile-18.04 --build-arg PKGSET_BRANCH=rock-osdeps-test .
    - docker run -d rock-osdeps/18.04 tail -f /dev/null

# overwrite the default build command
script:
    - docker run rock-osdeps/16.04 /bin/bash -c "source /home/docker/releases/master-18.01/env.sh; rock-log-level"
    - docker run rock-osdeps/18.04 /bin/bash -c "source /home/docker/releases/master-18.09/env.sh; rock-log-level"
    - docker run rock-osdeps/18.04 /bin/bash -c "source /home/docker/releases/master-19.06/env.sh; rock-log-level"
    - docker run rock-osdeps/18.04 /bin/bash -c "source /home/docker/releases/master-20.01/env.sh; rock-log-level"
